capstone/discussion/discussion/urls.py
from django.contrib import admin
# Using the import keyword allows access to the include function to allow use of the URLs/routes created in the previous step
# The include() function allows referencing other URLconfs. Whenever Django encounters include(), it chops off whatever part of the URL matched up to that point and sends the remaining string to the included URLconf for further processing
# The idea behind include() is to make it easy to plug-and-play URLs. Since todolist are in their own URLconf (todolist/urls.py), they can be placed under “/todolist/” or under “/content/todolist/”, or any other path root, and the app will still work
# You should always use include() when you include other URL patterns. admin.site.urls is the only exception to this
from django.urls import include, path

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

capstone/discussion/todolist/urls.py
from django.urls import path

from . import views

# The path() function can recieve four arguments
# We'll focus on the two arguments that are required, which are "route" and "view", and the third argument "name" which allows us to make global changes to the URL patterns of your project while only touching a single file
# Syntax
    # path(route, view, name)
app_name = 'todolist'
urlpatterns = [
    # /todolist route
    path('', views.index, name='index'),
    # /todolist/register
    path('register', views.register, name="register"),
    # /todolist/change_password
    path('change_password', views.change_password, name="change_password"),
    # /todolist/login
    path('login', views.login_view, name="login"),
    # /todolist/logout
    path('logout', views.logout_view, name="logout"),
    # /todolist/add_task
    path('add_task', views.add_task, name="add_task"),
    # /todolist/add_event
    path('add_event', views.add_event, name="add_event"),
    # /todolist/todoitem/<todoitem_id> route
    # The <int:todoitem_id> allows for creating a dynamic link where the todoitem_id is provided
    path('todoitem/<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
    # /todolist/<todoitem_id>/edit route
    path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
    # /todolist/<todoitem_id>/delete route
    path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
    # /todolist/event/<event_id> route
    path('event/<int:event_id>', views.event, name='view_event')
]

capstone/discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# [Section] Models
# Each model is represented by a class that subclasses django.db.models.Model. Each model has a number of class variables, each of which represents a database field in the model
# Each field is represented by an instance of a Field class – e.g., CharField for character fields and DateTimeField for datetimes. This tells Django what type of data each field holds.
# The name of each Field instance (e.g. task_name or date_created) is the field’s name, in machine-friendly format. You’ll use this value in your Python code, and your database will use it as the column name.
# Some Field classes have required arguments. CharField, requires that you give it a max_length. That’s used not only in the database schema, but in validation, as we’ll soon see.
# A Field can also have various optional arguments; in this case, we’ve set the default value of status to "pending.
class ToDoItem(models.Model):
    task_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField('date created')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class Event(models.Model):
    event_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="pending")
    date_created = models.DateTimeField('date created')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

capstone/discussion/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20)
    password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
    task_name = forms.CharField(label='Task Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label='Task Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)
    status = forms.CharField(label='Status', max_length=50)

class RegisterForm(forms.Form):
    # If fields are optional, using the "Model.save()" method will not work
    # Using the option "required=False" will allow the field to be optional when updating a record
    # task_name = forms.CharField(label='Task Name', max_length=50, required=False)
    username = forms.CharField(label='Username', max_length=50)
    first_name = forms.CharField(label='First Name', max_length=50)
    last_name = forms.CharField(label='Last Name', max_length=50)
    email = forms.CharField(label='Email', max_length=50)
    password = forms.CharField(label='Password', max_length=50)
    confirm_password = forms.CharField(label='Confirm Password', max_length=50)

class UpdateUserForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=50)
    last_name = forms.CharField(label='Last Name', max_length=50)
    password = forms.CharField(label='Password', max_length=50)
    # Since the new_password and confirm_password fields are optional when updating only the name of the user, we set the "required=False" option so that the record can be updating using only the name
    new_password = forms.CharField(label='New Password', max_length=50, required=False)
    confirm_password = forms.CharField(label='Confirm Password', max_length=50, required=False)

class AddEventForm(forms.Form):
    event_name = forms.CharField(label='Event Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)
    

capstone/discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
# The from keyword allows importing of necessary Classes, methods and other items needed in our application from the "django.http" package while the "import" keyword defines what we are importing from the package
# from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.hashers import make_password

# Local Imports
from .models import ToDoItem, Event
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, UpdateUserForm, AddEventForm

def index(request):
    todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
    event_list = Event.objects.filter(user_id=request.user.id)

    context = {
        "todoitem_list": todoitem_list,
        "event_list": event_list,
        "user": request.user
    }
    return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
    # The model_to_dict method allows to convert models into dictionaries
    # The .get() Model method allows to retrieve a specific record using it's primary key (pk)
    # todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
    todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
    # Instead of creating a context, we can pass the dictionary directly as the context of the view
    return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def register(request):

    context = {}

    if request.method == 'POST':

        form = RegisterForm(request.POST)

        if form.is_valid() == False:

            form = RegisterForm()

        else:

            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']

            duplicates = User.objects.filter(email=email)
            
            # if todoitem does not contain any duplicates
            if not duplicates and password == confirm_password:

                # Creates an object based on the "ToDoItem" model and saves the record in the database
                User.objects.create(username=username, first_name=first_name, last_name=last_name, email=email, password=make_password(password), is_staff=False, is_active=True)
                return redirect("todolist:login")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/register.html", context)

def change_password(request):

    authenticated_user = User.objects.get(pk=request.user.id)

    context = {
        "first_name": authenticated_user.first_name,
        "last_name": authenticated_user.last_name
    }

    if request.method == 'POST':

        form = UpdateUserForm(request.POST)

        if form.is_valid() == False:

            form = UpdateUserForm()

        else:

            username = authenticated_user.username
            password = form.cleaned_data['password']
            new_password = form.cleaned_data['new_password']
            confirm_password = form.cleaned_data['new_password']

            user = authenticate(username=username, password=password)

            if user is not None and new_password == confirm_password:
                
                authenticated_user.first_name = form.cleaned_data['first_name']
                authenticated_user.last_name = form.cleaned_data['last_name']

                print(authenticated_user.last_name)

                if new_password != "":
                    authenticated_user.set_password(form.cleaned_data['new_password'])

                authenticated_user.save(update_fields=['first_name','last_name'])

                return redirect("todolist:index")
            else:
                context = {
                    "error": True
                }

    return render(request, "todolist/change_password.html", context)

def login_view(request):

    context = {}

    # If this is a POST request we need to process the form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request
        form = LoginForm(request.POST)

        # Check whether the data is valid
        # Runs validation routines for all its fields and returns True and places the form's data in the "cleaned_data" attribute
        if form.is_valid() == False:

            # Returns a blank login form
            form = LoginForm()

        else:

            # Retrieves the information from the form
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            context = {
                "username": username,
                "password": password
            }
            
            if user is not None:
                # Saves the user’s ID in the session using Django's session framework
                login(request, user)
                return redirect("todolist:index")
            else:
                # Provides context with error to conditionally render the error message
                context = {
                    "error": True
                }

    return render(request, "todolist/login.html", context)

def logout_view(request):
    logout(request)
    return redirect("todolist:index")

def add_task(request):

    context = {
        "user": request.user
    }

    if request.method == 'POST':

        form = AddTaskForm(request.POST)

        if form.is_valid() == False:

            form = AddTaskForm()

        else:

            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']

            # Checks the database if a task already exists
            # By default the "filter" method searches for records that are case insensitive
            duplicates = ToDoItem.objects.filter(task_name=task_name, user_id=request.user.id)
            
            # if todoitem does not contain any duplicates
            if not duplicates:

                # Creates an object based on the "ToDoItem" model and saves the record in the database
                ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
                return redirect("todolist:index")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/add_task.html", context)


def update_task(request, todoitem_id):

    # Returns a queryset
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    context = {
        "user": request.user,
        "todoitem_id": todoitem_id,
        # Accessing the first element is necessary because the "ToDoItem.objects.filter()" method returns a queryset
        "task_name": todoitem[0].task_name,
        "description": todoitem[0].description,
        "status": todoitem[0].status
    }

    if request.method == 'POST':

        form = UpdateTaskForm(request.POST)

        if form.is_valid() == False:

            form = UpdateTaskForm()

        else:

            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']
            
            if todoitem:

                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status

                todoitem[0].save()
                return redirect("todolist:index")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):

    todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
    return redirect("todolist:index")

def add_event(request):

    context = {
        "user": request.user
    }

    if request.method == 'POST':

        form = AddEventForm(request.POST)

        if form.is_valid() == False:

            form = AddEventForm()

        else:

            event_name = form.cleaned_data['event_name']
            description = form.cleaned_data['description']

            # Checks the database if a task already exists
            # By default the "filter" method searches for records that are case insensitive
            duplicates = Event.objects.filter(event_name=event_name, user_id=request.user.id)
            
            # if todoitem does not contain any duplicates
            if not duplicates:

                # Creates an object based on the "ToDoItem" model and saves the record in the database
                Event.objects.create(event_name=event_name, description=description, date_created=timezone.now(), user_id=request.user.id)
                return redirect("todolist:index")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/add_event.html", context)

def event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    return render(request, "todolist/event.html", model_to_dict(event))

capstone/discussion/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add An Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate event found</p>
				{% endif %}
				<form action="{% url 'todolist:add_event' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="event_name">Event Name: </label>
					    <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Add Event">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

capstone/discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="task_name">Task Name: </label>
					    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Add Task">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

capstone/discussion/todolist/templates/todolist/change_password.html
{% extends 'base.html' %}

{% block title %}Update User Profile{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Update User Profile</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and passwords if they match</p>
			{% endif %}
			<form action="{% url 'todolist:change_password' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
				    <label for="first_name">First Name: </label>
				    <input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="last_name">Last Name: </label>
				    <input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="password">Current Password: </label>
				    <input class="form-control" id="password" type="password" name="password" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="new_password">New Password: </label>
				    <input class="form-control" id="new_password" type="password" name="new_password" maxlength="50">
				</div>

				<div class="mb-3">
				    <label for="confirm_password">Confirm New Password: </label>
				    <input class="form-control" id="confirm_password" type="password" name="confirm_password" maxlength="20">
				</div>

				<div class="text-center">
			    	<input class="btn btn-success" type="submit" value="Update Profile">
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}

capstone/discussion/todolist/templates/todolist/event.html
{% extends 'base.html' %}

{% block title %}View Event{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ event_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Events</a>
	</button>
	
</div>

{% endblock %}

capstone/discussion/todolist/templates/todolist/index.html
{% extends 'base.html' %}

<!-- Provides the title of the page to be provided in the template -->
<!-- This should correspond with the block name provided in the base.html file -->
{% block title %}Home{% endblock %}

<!-- Provides the content of the page to be provided in the template -->
<!-- This should correspond with the block name provided in the base.html file -->
{% block content %}
    {% if user.is_anonymous == False %}
        <h1 class="text-center my-3">Welcome {{ user.first_name }} {{user.last_name}}!</h1>

        {% if todoitem_list %}
            <div class="container">
                <div class="row">
                    <h3 class="text-center mb-3">My Tasks</h3>
                    <ul class="list-group col-lg-2 offset-lg-5 text-center">
                    {% for todoitem in todoitem_list %}
                        <a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
                            <li class="list-group-item">{{ todoitem.task_name }}</li>
                        </a>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <h3 class="text-center mb-3">My Tasks</h3>
                    <p class="text-center">No tasks have been created.</p>
                </div>
            </div>
        {% endif %}

        {% if event_list %}
            <div class="container">
                <div class="row">
                    <h3 class="text-center my-3">My Events</h3>
                    <ul class="list-group col-lg-2 offset-lg-5 text-center">
                    {% for event in event_list %}
                        <a href="{% url 'todolist:view_event' event.id %}" class="text-decoration-none">
                            <li class="list-group-item">{{ event.event_name }}</li>
                        </a>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <h3 class="text-center my-3">My Events</h3>
                    <p class="text-center">No events have been created.</p>
                </div>
            </div>
        {% endif %}

    {% else %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p> 
    {% endif %}
{% endblock %}

capstone/discussion/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and password</p>
			{% endif %}
			<form action="{% url 'todolist:login' %}" method="post">
				<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
				<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
				{% csrf_token %}

				<div class="mb-3">
				    <label for="username">Username: </label>
				    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
				    <label for="password">Password: </label>
				    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
			    	<input class="btn btn-success" type="submit" value="Login">
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}

capstone/discussion/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and passwords if they match</p>
			{% endif %}
			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
				    <label for="username">Username: </label>
				    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="first_name">First Name: </label>
				    <input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="last_name">Last Name: </label>
				    <input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="email">Email: </label>
				    <input class="form-control" id="email" type="text" name="email" value="{{ email }}" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="password">Password: </label>
				    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="50" required>
				</div>

				<div class="mb-3">
				    <label for="confirm_password">Confirm Password: </label>
				    <input class="form-control" id="confirm_password" type="password" name="confirm_password" value="{{ confirm_password }}" maxlength="20" required>
				</div>

				<div class="text-center">
			    	<input class="btn btn-success" type="submit" value="Register">
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}

capstone/discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}View To Do Item{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ task_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>
	
	<button class="btn btn-primary mx-1 text-decoration-none">
		<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
	</button>

	<button class="btn btn-danger mx-1 text-decoration-none">
		<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
	</button>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
	</button>
	
</div>

{% endblock %}

capstone/discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">Task not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="task_name">Task Name: </label>
					    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="mb-3">
					    <label for="status">Status: </label>
					    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Update Task">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}